CREATE TABLE IF NOT EXISTS `accounts` (
    `account_id` INT PRIMARY KEY AUTO_INCREMENT,
    `account_name` VARCHAR(255) NOT NULL UNIQUE,
    `balance` DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
    `last_updated` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
